theme: jekyll-theme-minimal
title: Conquer Space
logo: /assets/img/logo.png
description: A space themed grand strategy with emphasis on economy, society, and politics
google_analytics: UA-141722334-1
